### ISSUE TITLE
[feat] Enlarge photo when some clicks on it

### ISSUE THREAD

**Issue by Mayuresh-22** [Mayuresh-22/Minglr#111]
## What is expected?
Nothing happens when clicking on a photo in the feed or account feed. It would be great if the photo were enlarged in the centre of the screen with gaps on top and bottom, and the background becomes dimmed, and when the user clicks outside of the photo area the enlarged photo disappears and things return to normal.

## What you can do?
Try building a simple JS logic that can handle the above functionality

## Things to remember
Your design should be responsive i.e it should look great on both desktop and mobile devices.

**Comment by ankit1576** [comment]
assign it to me i want to add this feature

**Comment by Mayuresh-22** [comment]
Okay @ankit1576 I'll assign it to you. Make sure you have understood all the requirements clearly.

**Comment by Mayuresh-22** [comment]
solved by #115
