### ISSUE TITLE
Social Media Buttons Not Functioning Properly (Facebook, Twitter, Instagram, YouTube)

### ISSUE THREAD

**Issue by HimanshuGitCode** [Mayuresh-22/Minglr#123]
The social media buttons for Facebook, Twitter, Instagram, and YouTube on our website are not functioning as expected. Clicking on these buttons does not redirect users to the respective social media pages.

![Screenshot (1251)](https://github.com/user-attachments/assets/d777257c-f91d-4bbc-bf4f-ca7ee1d60941)
![Screenshot (1250)](https://github.com/user-attachments/assets/c23d26a2-7b03-4392-9d80-add3ffc050bc)

**Comment by Mayuresh-22** [comment]
Yes, you can go ahead and start working on this issue I'll supply necessary social links in next comment

**Comment by Mayuresh-22** [comment]
Here are social links:
Github: https://github.com/Mayuresh-22/Minglr
Twitter: https://x.com/mayuresh_empire
Linkedin: https://www.linkedin.com/in/mayureshchoudhary/

For now, these links are sufficient, you may need to remove & add new icons for this links you may use https://iconbuddy.com/

**Comment by HimanshuGitCode** [comment]
Working on this I will rase PR as soon as possible.

**Comment by HimanshuGitCode** [comment]
A PR has been raised. Please check and merge it into the respective branch.

**Comment by Mayuresh-22** [comment]
Thank you for raising an issue and making a PR to solve it. I've merged the PR and closing this issue as completed.
