### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by Mayuresh-22** [Mayuresh-22/Minglr#13]
## Descritption
Currently, we have a search functionality on the site (visit the /account.php page). The search logic implemented only searches for the usernames (matches the username) and has no partial or fuzzy word search if searching returns no row from the database it simply prints No user found that's it.

## Solution needed
We aim to enhance this user search functionality by allowing partial and fuzzy word searches. Specifically, we want to enable users to search for other users not only by their usernames but also by their first and last names. For example, if a user searches for "mayuresh," the search should return users with the search query present in their username, first name, or last name, such as **mayuresh**22, **mayuresh**10, and xyz_**mayuresh**.

This issue will be assigned under #hactoberfest2023
(Search logic is written in account.php and back/search.php)

**Comment by Virtual4087** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by Mayuresh-22** [comment]
Are you working on this issue? If yes I'll assign it to you.

**Comment by Virtual4087** [comment]
sorry but i can't rn

**Comment by Jenis07** [comment]
i can work on this issue so can you assign it to me?

**Comment by Mayuresh-22** [comment]
Any updates @Jenis07

**Comment by Mayuresh-22** [comment]
> Any updates @Jenis07

.

**Comment by 4darsh-Dev** [comment]
if the issue is not solved, @Mayuresh-22  can you assign it to me

**Comment by Mayuresh-22** [comment]
Yus the issue is still not resolved. I will assign it to @4darsh-Dev

**Comment by Mayuresh-22** [comment]
Any updates? @4darsh-Dev

**Comment by Jenis07** [comment]
I have solve this issue..
![image](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/100338684/e285c251-bd74-465f-bc5a-8bbbcf633cc5)

**Comment by Jenis07** [comment]
As in the above screenshot i have search only te in the search and i got the user that i have store as the test_2

**Comment by Jenis07** [comment]
![image](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/100338684/1222a20b-0183-407b-b179-c143986a19ea)
when more than one username user found i have also showing the that more users of same matching result...

**Comment by Mayuresh-22** [comment]
Hello @Jenis07, I was a bit busy with other tasks so I could not revert.

You have done a great job, so instead of showing the whole profile at the time of searching what if we just show the search results just like **Threads/Instagram App** Eg: A list containing profile pic, username and full name?

**Comment by Jenis07** [comment]
Yes but i have already make pull request of it.. so what i have next to do?
can i make another changes? and make design like you have said...

**Comment by Mayuresh-22** [comment]
yes, you can make the changes so that I can merge it finally.

**Comment by Jenis07** [comment]
okay sir i am working on it.. and i will update the code.. but please can you please accept fast if this is acceptable? then because the hectoberfest is ending soon..

**Comment by Mayuresh-22** [comment]
"Absolutely, @Jenis07! I understand how important it is for you to complete your Hacktoberfest 2023 challenge, and I can assure you that I will merge your submission as soon as possible. Thank you for your hard work and dedication!"

**Comment by Jenis07** [comment]
Yes sir i will submit the new search UI by tomorrow evening..

**Comment by Jenis07** [comment]
sir i have created the new UI. so i want to show it...
![image](https://github.com/Mayuresh-22/Minglr/assets/100338684/3b067611-eb19-4066-90ac-bab873353ac4)
can you please respond it fast?.. so i can make the commit it on the repo...

**Comment by Mayuresh-22** [comment]
yup great @Jenis07

**Comment by Jenis07** [comment]
Okay sir i am getting commit it on the..

**Comment by Jenis07** [comment]
i have created the new pull request..

**Comment by Mayuresh-22** [comment]
This issue is resolved completely by @Jenis07 thank you for your valuable contribution
