### ISSUE TITLE
Updating Title, Adding meta description, keywords

### ISSUE THREAD

**Issue by Mayuresh-22** [Mayuresh-22/Minglr#22]
## Issue Description
Currently, website only has the "Minglr" as a title and no meta description or keywords.

## What I am looking for
Therefore, I am looking for updating the title to "Minglr - Social Networking Site" and adding meta description, keywords (description and keywords should be relevant, you can refer readme file to know about the project and platform)

I anyone interested to solve this issue your are very much welcome.

**Comment by Nandini99-git** [comment]
I would like to work on this, please assign me.

**Comment by Mayuresh-22** [comment]
Sure, @Nandini99-git. I will assign it to you.

**Comment by Mayuresh-22** [comment]
any updates @Nandini99-git ?

**Comment by Nandini99-git** [comment]
@Mayuresh-22 , sorry for the delay
I am working on it, l will report within 2 days

**Comment by Mayuresh-22** [comment]
Okay, no issues

**Comment by Mayuresh-22** [comment]
PR #28 solved the issue
