### ISSUE TITLE
[bug]: Improve Code Formatting for Enhanced Readability

### ISSUE THREAD

**Issue by purnasth** [Mayuresh-22/Minglr#26]
# Issue Title: Improve Code Formatting for Enhanced Readability

## Issue Description
The current codebase's PHP sections lack consistent formatting, leading to reduced readability and maintainability. To improve comprehension and ease maintenance, it's essential to enhance the formatting of the PHP code.

## Additional Information
The implementation of better code formatting is crucial for a more maintainable and understandable codebase. Clear and consistent code formatting significantly benefits developers in comprehending, extending, and maintaining the code.

Assigning this issue to someone experienced with PHP and familiar with the specific style guidelines will ensure a more coherent and readable code structure.

**Comment by Mayuresh-22** [comment]
Do you want to work on this issue?

**Comment by itsmeabhishek03** [comment]
Hey @Mayuresh-22 can i work on it. Please assign it to me under SWOC.

**Comment by pankhuri92** [comment]
Hi @Mayuresh-22! I would be glad to contribute here, if you could assign it to me.

**Comment by Mayuresh-22** [comment]
Hey @itsmeabhishek03, sure you can work on the issue but SWOC event will start from 1st of Jan.
So I'll just suggest you to wait for now.

**Comment by Mayuresh-22** [comment]
Hey @pankhuri92, as I mentioned earlier SWOC event will start from 1st of Jan.
So I'll just suggest you to wait for now and I'm sure you'll get some or the other issues to work on in Minglr.

**Comment by itsmeabhishek03** [comment]
> Hey @Mayuresh-22 can i work on it. Please assign it to me under SWOC.

So will you assign this issue to me on 1st Jan or you will assign it to someone else?

**Comment by Mayuresh-22** [comment]
> > Hey @Mayuresh-22 can i work on it. Please assign it to me under SWOC.
> 
> So will you assign this issue to me on 1st Jan or you will assign it to someone else?

I can't guarantee you but most probably yes I'll assign this issue to you.

**Comment by itsmeabhishek03** [comment]
> > > Hey @Mayuresh-22 can i work on it. Please assign it to me under SWOC.
> > 
> > 
> > So will you assign this issue to me on 1st Jan or you will assign it to someone else?
> 
> I can't guarantee you but most probably yes I'll assign this issue to you.

Ok as you say 👍

**Comment by Mayuresh-22** [comment]
hello @itsmeabhishek03, as said before I am assigning this issue to you. You can start working on it.

**Comment by itsmeabhishek03** [comment]
Okay thank you @Mayuresh-22
