### ISSUE TITLE
Making "Send Message" button responsive for Mobile divces

### ISSUE THREAD

**Issue by Mayuresh-22** [Mayuresh-22/Minglr#3]
# Description
Currently Send Message button looks perfect for Desktop view, but not for mobile.
This button should be responsive inorder to look great on mobile devices.

(In order to work on this issue firstly setup project on your local machine, and register/login to look for "Send Message" button on the profile page of other users.

---
# Screenshots

## Mobile View
![Capturesadfas](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/111348926/f4130cd8-ba55-4656-936b-b35fbc12354b)

## Desktop View
![Screenshot (94)](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/111348926/73045b8c-3092-45a5-90fa-537e88c9a9c2)

**Comment by saffi-786** [comment]
Hey @Mayuresh-22 ! I'm interested in fixing this issue. 
Please assign this issue to me.

**Comment by yashi-15** [comment]
I would like to fix this issue. Please assign it to me under hacktoberfest.

**Comment by Ahnaf-codes** [comment]
@Mayuresh-22 I can fix this issue. I have experience fixing various css responsiveness issues for various websites. So please assign it to me

**Comment by Mayuresh-22** [comment]
> Hey @Mayuresh-22 ! I'm interested in fixing this issue. Please assign this issue to me.

Hey, I am assigning this issue to you @saffi-786

**Comment by Mayuresh-22** [comment]
> I would like to fix this issue. Please assign it to me under hacktoberfest.

Hey @Ahnaf-codes, I'll surely create new issues in this repo and will assign it to you. I guarantee you that you'll not find short of quality issues in this repo.

**Comment by Mayuresh-22** [comment]
> I would like to fix this issue. Please assign it to me under hacktoberfest.

Hey @yashi-15 , I'll surely create new issues in this repo and will assign it to you. I guarantee you that you'll not find short of quality issues in this repo for Hacktoberfest 2023

**Comment by saffi-786** [comment]
@Mayuresh-22 thank you for assigning the issue to me.

**Comment by saffi-786** [comment]
@Mayuresh-22 can you plz help solving this as I don't have much knowledge of PHP or MySQL. I have to access the account page to modify the CSS 
<img width="793" alt="Screenshot 2023-10-01 002258" src="https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/112777024/979a8543-128f-4572-930d-0db381851c82">
styling of the button.

**Comment by saffi-786** [comment]
@Mayuresh-22 can you plz help solving this as I don't have much knowledge of PHP or MySQL. I have to access the account page to modify the CSS styling of the send message button
<img width="793" alt="Screenshot 2023-10-01 002258" src="https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/112777024/76f032f5-ff31-4613-87a8-bb9ba89fd7fc">

**Comment by Mayuresh-22** [comment]
> @Mayuresh-22 can you plz help solving this as I don't have much knowledge of PHP or MySQL. I have to access the account page to modify the CSS styling of the send message button <img alt="Screenshot 2023-10-01 002258" width="793" src="https://user-images.githubusercontent.com/112777024/271790476-76f032f5-ff31-4613-87a8-bb9ba89fd7fc.png">

Hey @saffi-786, the error you are facing is because of the misconfiguration between password mentioned in the connection.php file and the password of MySQL.

But have downloaded and installed the XAMPP server?

**Comment by saffi-786** [comment]
Yes, Sir, I have downloaded and installed the XAMPP server, and it's showing the same error on the browser when I enter a username on the search field in the accounts.php
Do I need first to register to view all the pages?

**Comment by Mayuresh-22** [comment]
> Yes, Sir, I have downloaded and installed the XAMPP server, and it's showing the same error on the browser when I enter a username on the search field in the accounts.php Do I need first to register to view all the pages?

Ohkay, 
## Changing File content
1) Open your **connection.php** file from **db** folder.
2) Change the **$user** variable value to **root** (in string double quotes)
3) Change the **$pswd** variable value to **""** (Empty string)
4) Start your xampp server and start **Apache and MySQL** (every time you work on this project)

## Creating Database
5) Go to **http://localhost/phpmyadmin/** and click on "new" option from left side bar.
6) Enter **minglr** and press create
7) Press **import** option from top bar and chose the **.sql** file from the **db** folder and click Import

Now you are done option project in the browser create a new account and you are done.
I know these steps are a bit tricky but even if you face any issue I am there for you.

**Comment by saffi-786** [comment]
It's showing this error. 

<img width="950" alt="image" src="https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/112777024/466f59b3-e7ed-4236-b41d-c700c424e601">

**Comment by Mayuresh-22** [comment]
> It's showing this error.
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/112777024/271837820-466f59b3-e7ed-4236-b41d-c700c424e601.png">

Start MySQL in XAMPP

**Comment by saffi-786** [comment]
I'm getting this error when I'm starting the MySQL

<img width="488" alt="image" src="https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/112777024/ad33cc53-93e2-457c-925b-1d9442bf3eca">

**Comment by Mayuresh-22** [comment]
Have you previously installed any MySQL server on your machine?

**Comment by saffi-786** [comment]
Yes I installed MySQL on my system some days back

**Comment by Mayuresh-22** [comment]
Yes, it's causing the issue because MySQL by default works on port 3306.
So I suggest you change the port number of MySQL in XAMPP (which will not affect other MySQL servers)

## Follow these steps to change the MySQL server port in XAMPP:

1) Open your XAMPP server

2) Click on the "Config" option of the MySQL module & click on **my.ini** (Shown below)
![Screenshot (95)](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/111348926/fca88dd1-f6eb-49f6-8e09-d2507d93bc30)

3) Open with any text editor, now wherever you see **3306** change it with a new port number (here, 3307) throughout the file.
![Screenshot (96)](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/111348926/a444b55a-0610-40d3-9236-99add18a1eb9)


And you are done hopefully, this will solve your issue.
(I suggest you update the git repo that you have cloned on your machine because different changes were made to the repo)

**Comment by saffi-786** [comment]
I changed the MySQL port.
Now MySQL is running, but it is still denying access on http://localhost/phpmyadmin/

<img width="495" alt="image" src="https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/112777024/38e2ee99-55a7-4c38-a472-2ca96955a23c">

<img width="767" alt="image" src="https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/112777024/161e5abf-6bc9-42ad-af9a-f3cefd3991c7">

**Comment by Mayuresh-22** [comment]
Hey @saffi-786, I guess I missed one step, change the port 3306 also in **php.ini** file. (Shown below)

![Screenshot (97)](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/111348926/6529d758-3d03-47fa-a542-2b1fdfa6ec1c)

![123Capture](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/111348926/d4f6366e-ec5e-4049-9f27-9555423720bb)
(Change throughout the file)

**Comment by saffi-786** [comment]
Followed the above steps 
Still the same error

**Comment by Mayuresh-22** [comment]
You can try removing the previously installed MySQL server.

**Comment by Mayuresh-22** [comment]
Anyone working on this?

**Comment by abneribeiro** [comment]
hey bro, I was looking at your project and found it very interesting.

**Comment by 4darsh-Dev** [comment]
if the task is not completed, could you please assign it to me

**Comment by Mayuresh-22** [comment]
> hey bro, I was looking at your project and found it very interesting.

Thank You so much for your words @abneribeiro

**Comment by pankhuri92** [comment]
I would be interested to resolve the issue incase nobody has been assigned.

**Comment by KhushiAgarwal-01** [comment]
I am ready to solve this issue  if the issue has not been assigned or solved yet

**Comment by Mayuresh-22** [comment]
Hey @KhushiAgarwal-01, SWOC hasn't started yet and will be starting from the 1st of Jan but still, you can get familiar with the codebase and I am sure you'll get something to work on.

**Comment by Mayuresh-22** [comment]
@pankhuri92 I am assigning this issue to you, start working on it.

**Comment by pankhuri92** [comment]
Thanks a lot @Mayuresh-22 ! Will keep you updated.

**Comment by pankhuri92** [comment]
@Mayuresh-22, I would like to bring in to ur info that there isn't any send message button any more as I went through the site. So  I might have to add the send button there. 

![Screenshot 2024-01-01 164617](https://github.com/Mayuresh-22/Minglr/assets/138357063/872d54b1-59d1-45e4-9c38-6a5eae638976)
![Screenshot 2024-01-01 164637](https://github.com/Mayuresh-22/Minglr/assets/138357063/087b7b6e-b074-453a-b6f2-cb97f18c9b86)

**Comment by Mayuresh-22** [comment]
Okay @pankhuri92, I'll check that out.

**Comment by Mayuresh-22** [comment]
This issue has been successfully solved by @pankhuri92 under SWOC S4 2024
