### ISSUE TITLE
[feat] Add Favicon to the site

### ISSUE THREAD

**Issue by Mayuresh-22** [Mayuresh-22/Minglr#32]
# Discription
Currently, the site doesn't have a favicon and it looks weird. (Favicon is just an image displayed beside the page title)

# What is expected?
You have to add a favicon to the pages of the platform, you might need to perform the same step on multiple pages.

# Resources
Sharing Favicon image.
https://github.com/Mayuresh-22/Minglr/blob/main/img/favicon_minglr.png

**Comment by Thanush19** [comment]
i'll work on this @Mayuresh-22

**Comment by Fictioknox** [comment]
I can work on this issue @Mayuresh-22

**Comment by Mayuresh-22** [comment]
I'll assign them on the 1st of JAN

**Comment by Mayuresh-22** [comment]
Hey @Thanush19, I am assigning this issue to you. Feel free to contact me if you need help setting up the project on your local machine.

**Comment by Mayuresh-22** [comment]
As I have assigned another issue to @Thanush19, I'll assign this issue to @Fictioknox. Feel free to contact me if you need help setting up the project on your local machine.

**Comment by Fictioknox** [comment]
@Mayuresh-22 Thank you for assigning this issue to me. If I have any problem I'll be sure to contact you.

**Comment by Mayuresh-22** [comment]
Congratulations @Fictioknox on your first contribution to **Minglr** 🎉. You did as expected.
