### ISSUE TITLE
Add cursor pointer

### ISSUE THREAD

**Issue by itsmeabhishek03** [Mayuresh-22/Minglr#36]
On user account page we can add cursor pointer on both "post" and "choose file" button for better user expierence. 

![image](https://github.com/Mayuresh-22/Minglr/assets/104294494/458c2cf1-9c3c-4487-9887-1c9aaa5a0a4c)

**Comment by Amine2000s** [comment]
if this issue is not assigned to anyone
Could you please assign me this issue under #SWOC24 @Mayuresh-22

**Comment by itsmeabhishek03** [comment]
> if this issue is not assigned to anyone Could you please assign me this issue under #SWOC24 @Mayuresh-22

Hey @Amine2000s this issue is already assigned to me. I am sure you will get some other issues all the best  👍
