### ISSUE TITLE
Logout Functionality 

### ISSUE THREAD

**Issue by ak4631** [Mayuresh-22/Minglr#37]
There is an error logging out in the session. Can I fix it.

**Comment by Mayuresh-22** [comment]
Sure @ak4631 thanks for reporting it. You can start working on it.

**Comment by ak4631** [comment]
Ok@Mayuresh-22 Thanks For the Opportunity.

**Comment by ak4631** [comment]
Hello @Mayuresh-22 I am Done Resolving the Issue Please make sure to check it out. Please Review It.

**Comment by Mayuresh-22** [comment]
Hello @ak4631 you can make a pull request then.

**Comment by ak4631** [comment]
Yes I have made a Pull Request @Mayuresh-22

**Comment by Mayuresh-22** [comment]
Solved by PR #50
