### ISSUE TITLE
Check button functionality in mobile responsiveness - enhancement

### ISSUE THREAD

**Issue by atmaram-kambli** [Mayuresh-22/Minglr#38]
Current Situation: 
When we click on the check button, side navbar is displayed, and the check button remains unchanged.

Enhancement: 
We can enhance the UI by transforming the current 'Three bar check btn' to the 'cross btn' whenever the use clicks on it with beautiful transition effect and vice versa.

current UI: 
![Screenshot 2024-01-01 134747](https://github.com/Mayuresh-22/Minglr/assets/118362436/ba7448d4-8fa3-4118-99e2-080923064398)

Expected Outcome will look like follows: 
![Untitled design (1)](https://github.com/Mayuresh-22/Minglr/assets/118362436/e188b740-693e-4710-b0ae-bec64738e8b5)
(This is only edited image)

**Comment by Mayuresh-22** [comment]
Hey @atmaram-kambli.
I liked your idea, I'll assign this issue to you. You can start working on it.
