### ISSUE TITLE
Responsive title bar

### ISSUE THREAD

**Issue by pankhuri92** [Mayuresh-22/Minglr#40]
The title/name of the site i.e., 'minglr' is not in its position in the mobile version. @Mayuresh-22 kindly assign me the issue to fix it.

![Screenshot 2024-01-01 164617](https://github.com/Mayuresh-22/Minglr/assets/138357063/1bc4354e-fb48-4258-9189-fd6ba728bb5a)

**Comment by Mayuresh-22** [comment]
Okay @pankhuri92 you can start working on it i'll asign it to you

**Comment by pankhuri92** [comment]
![Screenshot 2024-01-01 222444](https://github.com/Mayuresh-22/Minglr/assets/138357063/3e4a6a57-0a66-4bde-85ec-557f4d3f3e56)
![Screenshot 2024-01-01 222454](https://github.com/Mayuresh-22/Minglr/assets/138357063/89103a16-0afc-4048-b54a-0e6312a69358)
 I have made it responsive. Kindly review.

**Comment by Mayuresh-22** [comment]
Ohh that's great I'll check that out now.

**Comment by Mayuresh-22** [comment]
Closing this issue as it is solved by PR #45
