### ISSUE TITLE
Responsive message page

### ISSUE THREAD

**Issue by pankhuri92** [Mayuresh-22/Minglr#42]
The message/conversation page of the site is not responsive at all. @Mayuresh-22 could you pls assign me the issue to fix it.
![Screenshot 2024-01-01 175507](https://github.com/Mayuresh-22/Minglr/assets/138357063/6b25bcb4-3fdc-4690-a2d0-b16f6f65d583)
![Screenshot 2024-01-01 175517](https://github.com/Mayuresh-22/Minglr/assets/138357063/a58a119f-ac01-4cce-8dcf-df6bb72be34b)

**Comment by Mayuresh-22** [comment]
Good observation @pankhuri92, I'll assign it to you...

**Comment by Mayuresh-22** [comment]
@pankhuri92 are you still working on the issue?

**Comment by pankhuri92** [comment]
Yes, I have committed the changes.
