### ISSUE TITLE
[feat] Add NIGHT MODE feature

### ISSUE THREAD

**Issue by raghav1482** [Mayuresh-22/Minglr#46]
**Adding night mode feature/color palette would add to the appearance of the website.** 

*FUNTIONING : 
-> on clicking button there would be switch in the ui color modes

**Could you please assign me this issue under **#SWOC24**  @Mayuresh-22**

**Comment by nsrs-78** [comment]
Instead of adding just two modes....I'd like to add a colour palette here . showing a demo like this .....
![Screenshot 2024-01-01 212651](https://github.com/Mayuresh-22/Minglr/assets/137761848/1ae8906b-f6a3-443b-8143-608be52381d0)
Can I contribute to it under SWOC'24 ? @Mayuresh-22

**Comment by raghav1482** [comment]
Kindly assign me this issue under SWOC24
@Mayuresh-22

**Comment by KhushiAgarwal-01** [comment]
I can work on this issue .can you assign me his issue under SWO24

**Comment by gauravver13** [comment]
Kindly assign this issue to me under SWOC24 @Mayuresh-22

**Comment by Mayuresh-22** [comment]
hello @raghav1482, I see that you are already working on two issues. To give a fair chance to everyone I'll need to assign this issue to someone else. Therefore I'll assign this issue to @nsrs-78 (still you want to solve this issue?).
And @KhushiAgarwal-01,@gauravver13  don't worry. There are dozens of issues I'll be creating in the coming few days.

**Comment by nsrs-78** [comment]
yea  sure I'm ready to start

**Comment by Mayuresh-22** [comment]
@itsneha15 are you still working on it?

**Comment by Mayuresh-22** [comment]
Kindly reply to this comment if you are interested in working on this issue and I'll assign it on a first-come, first-served basis.
