### ISSUE TITLE
[bug] Photos not visible in Photos section of profile.

### ISSUE THREAD

**Issue by raghav1482** [Mayuresh-22/Minglr#48]
Photos not visible in Photos section of profile.

Kindly assign me this issue under **#SWOC24** @Mayuresh-22

**Comment by Mayuresh-22** [comment]
Yes, @raghav1482 I am assigning this issue to you. You can start working on it.

**Comment by Mayuresh-22** [comment]
@raghav1482 are you still working on the issue?

**Comment by raghav1482** [comment]
yes i am .

**Comment by raghav1482** [comment]
I have completed it ... minor changes left
