### ISSUE TITLE
Enhancing User Experience with Hover Effects

### ISSUE THREAD

**Issue by ayushichoudhary-19** [Mayuresh-22/Minglr#52]
I've noticed that the current version of the website could benefit from the addition of hover effects. These effects can enhance the overall user experience and make the interface more interactive. I propose implementing hover effects on various sections of the website, mainly the LOGIN and REGISTER buttons and other buttons in the forms.

![image](https://github.com/Mayuresh-22/Minglr/assets/73214455/bf977b2c-635e-4498-9a37-84f0b918c9ce)
-

 I'm interested in working on this issue.

**Comment by Mayuresh-22** [comment]
That's a great suggestion @ayushichoudhary-19, I'll assign this issue to you then. Just go through the setup steps in readme file and you are all set.

**Comment by Mayuresh-22** [comment]
Closing this issue, solved by #53
