### ISSUE TITLE
[Feat]:Adding font color white on the footer to enhance the UI experience

### ISSUE THREAD

**Issue by SulagnaKundu** [Mayuresh-22/Minglr#55]
**Describe the feature**
adding hover effect on the footer section

**To Reproduce**
1. Go to website
2. Scroll down to the last footer section
3. white font color could be added in the footer section

**Screenshots/Videos**
![image](https://github.com/Mayuresh-22/Minglr/assets/103977344/284a9535-52d0-4104-a245-ba447f6c94bc)
Want to change the text color to white to enhance the UI experience

**Comment by SulagnaKundu** [comment]
I want to work on this issue. Can you please assign me this issue?

**Comment by vrun1208** [comment]
@Mayuresh-22 , I want to work on this one!

**Comment by Mayuresh-22** [comment]
Hey @SulagnaKundu,
Nice idea. You can start working on it. I'll assign it to you.

**Comment by GauriGA** [comment]
I want to work on this issue. Can you please assign me this issue?

**Comment by Mayuresh-22** [comment]
Hey @GauriGA, you can look for other open issues at https://github.com/Mayuresh-22/Minglr/issues If not you can create your own issue and I'll assign it to you.
