### ISSUE TITLE
Additional empty white space between the ":" and the actual profile informations and also no space between "name","lastname"...ect and ":"

### ISSUE THREAD

**Issue by Amine2000s** [Mayuresh-22/Minglr#60]
![unimportantwhitespace](https://github.com/Mayuresh-22/Minglr/assets/92222814/3d664353-700c-4ee2-9ddb-00d15499d054)

Can  you please assign me this issue under #SWOC24 @Mayuresh-22
*the email is brushed on purpose by me *

**Comment by Mayuresh-22** [comment]
Oh okay then @Amine2000s, you can start working on this issue. Try to make it look consistent. I'll assign this issue to you.

**Comment by Amine2000s** [comment]
@Mayuresh-22 the issue is fixed , i am waiting for my first pull request to be merged so i can pull request again.



![issue_fixed](https://github.com/Mayuresh-22/Minglr/assets/92222814/528c16c4-5a08-4444-995b-fdcbefd6c89a)

**Comment by Mayuresh-22** [comment]
yes @Amine2000s. your changes were reflected in your previous PR. Don't worry I'll mark it as seperate

**Comment by Mayuresh-22** [comment]
solved by #59 closing this issue
