### ISSUE TITLE
[feat] Adding a Confirmation Pop up Screen before Logout Action

### ISSUE THREAD

**Issue by Amine2000s** [Mayuresh-22/Minglr#61]
i believe i can add a pop-up Screen to Let the User Confirm his Logout 

please Assign it to me Under #swoc24 @Mayuresh-22

**Comment by Mayuresh-22** [comment]
yes great idea @Amine2000s, I am assigning this issue to you then. You can start working on it.

**Comment by Amine2000s** [comment]
@Mayuresh-22  Completed All my assigned issues , waiting for Pull pull request to be merged and the assignments to start working

**Comment by Mayuresh-22** [comment]
@Amine2000s, do you have any updates on this issue? If not, I will unassign it.

**Comment by Amine2000s** [comment]
hey @Mayuresh-22 , i will deliver it under 24hour

**Comment by Amine2000s** [comment]
Hey @Mayuresh-22 , i am very soory
But i am going throught an emergency conditions, i will need extra 24 hours

**Comment by Amine2000s** [comment]
![confirmation logout proof ](https://github.com/Mayuresh-22/Minglr/assets/92222814/bea8e5ca-11d0-4bc6-a087-cdf16cd6c5f8)


@Mayuresh-22  currentlly working on it , just some Css alignmnet and few test and the pull reqeuest will be sent

**Comment by Amine2000s** [comment]
https://github.com/Mayuresh-22/Minglr/assets/92222814/79329fb8-e215-436c-8214-a5c9651b97b4






i am currently facing some problems to redirect it to the back/logout.php page , i used many ways and it didn't work 
(like inside script tags , making a function that do that in the js file )

do you have any suggestion  ? @Mayuresh-22

**Comment by Mayuresh-22** [comment]
> feed-logout.mp4 
> i am currently facing some problems to redirect it to the back/logout.php page , i used many ways and it didn't work (like inside script tags , making a function that do that in the js file )
> 
> do you have any suggestion ? @Mayuresh-22

I'll analyse your changes and will get back to you in short.

**Comment by Mayuresh-22** [comment]
Okay @Amine2000s, 
Once the confirmation box popups you can set the click function on the yes confirm button and once it is clicked you can redirect it with the `window.location.href = "back/logout.php";` line.

**Comment by Amine2000s** [comment]
I did it , but it didn't redirect me to anything
