### ISSUE TITLE
Add RegEx (regular expression to the email and password registration )

### ISSUE THREAD

**Issue by Amine2000s** [Mayuresh-22/Minglr#62]
Hi again @Mayuresh-22 I believe i can add Regular expression control to the email Input so that user can fill a correct email function 
and the same too 
![gmail_reg_ex](https://github.com/Mayuresh-22/Minglr/assets/92222814/c90f198e-d850-4df5-9221-66f6bf2c37cb)
for password to input a moderate and secure password

**Comment by Mayuresh-22** [comment]
I see that you are currently working on two issues. I would suggest you complete on so that I can assign this to you.

**Comment by GauriGA** [comment]
Can you assign me this issue?

**Comment by Amine2000s** [comment]
I really Wanted to Work on this issue , Anyway , best of luck brother @GauriGA
