### ISSUE TITLE
Feat: Enhance the homepage 

### ISSUE THREAD

**Issue by Yatin12527** [Mayuresh-22/Minglr#65]
I'd love to enhance the homepage for reference these are  my other works
![c3312a9c-9807-46a2-a2b2-5bf0cc407556](https://github.com/Mayuresh-22/Minglr/assets/134225415/958a85ce-6bd3-4840-8e8e-bfa83201bb2e)
![fc8f37e9-30a0-4704-a831-c465acda6e3d](https://github.com/Mayuresh-22/Minglr/assets/134225415/dd07fe68-86fb-4d6e-bdbf-a95cff9209fb)

**Comment by Mayuresh-22** [comment]
I would greatly appreciate if you maintain the current theme while enhancing it. Do you have any idea about doing it?

**Comment by Yatin12527** [comment]
> I would greatly appreciate if you maintain the current theme while enhancing it. Do you have any idea about doing it?

the screen looks too empty if u want to strictly maintain the background then i can work a bit with button styling hover effects and if thats not the compulsion then i can incorporate some bg preferably a custom edited image which i'll make according to theme and judging from the current theme it looks to be white and sky bluish. Thats just my approach of doing it i'd appreciate you adding something more on it and yea i'll ping you on discord lets discuss more there :)
