### ISSUE TITLE
[enhancement] Potential Changes to Footer for Improved User Experience 

### ISSUE THREAD

**Issue by KaranSharma73** [Mayuresh-22/Minglr#67]
To ensure a smooth transition , I would like to enhance the footer of the login page and also in the navigation bar. I also want to add an anchor tag in your name at footer to connect it with your Linkdin account.

**Comment by KaranSharma73** [comment]
@Mayuresh-22

**Comment by Mayuresh-22** [comment]
Can you be specific about what enhancement would you like to do in the footer and navbar?

**Comment by GauriGA** [comment]
@Mayuresh-22 I have a few ideas regarding this issue. We can consider using a hamburger menu for mobile devices to save space. We can also integrate social media icons in the footer. 
If you are not assigning this issue to @KaranSharma73, can you please assign this to me?

**Comment by Mayuresh-22** [comment]
@KaranSharma73 it seems you are not active in this conversation that is the reason I'll need to assign this issue to someone else.
@GauriGA you can start working on the issue. 
Note: Hamburger for mobile devices is already so there's no need to create one.
You can enhance the footer of the page and try to make it look and feel attractive.
Your changes are always welcomed.
Also if you make any changes to footer make sure they are reflected on the every page of the platform

**Comment by GauriGA** [comment]
@Mayuresh-22 Can I add some social media icons?

**Comment by Mayuresh-22** [comment]
> @Mayuresh-22 Can I add some social media icons?

Yes, you can.
