### ISSUE TITLE
Change the color of the text in footer section

### ISSUE THREAD

**Issue by blindaks** [Mayuresh-22/Minglr#69]
The black color is not properly visible over the blue background. We can change its color.
<img width="851" alt="image" src="https://github.com/Mayuresh-22/Minglr/assets/128223364/3e108563-51a3-4e67-a355-ef20a3a24e51">

Please assign this issue to me.

**Comment by Mayuresh-22** [comment]
This issue is already solved & will be reflected on the live site in a few hours.
