### ISSUE TITLE
Improving the UI of account page .

### ISSUE THREAD

**Issue by Owais24code** [Mayuresh-22/Minglr#72]
@Mayuresh-22 
The account page UI looks in unstructured way as the footer is not in its correct place.
and also want to make UI changes to the account page as it looks less impressive.
if you find this issue correct, please assign this to me under the SWOC24 label.
![Screenshot 2024-01-04 215629](https://github.com/Mayuresh-22/Minglr/assets/112776960/b9741268-b68c-42b3-b5c7-f6babfa5ee3d)

**Comment by Nitinshukla88** [comment]
Please assign this issue to me @Mayuresh-22

**Comment by Mayuresh-22** [comment]
Hello @Owais24code, I would like to know what enhancement you are planning to make.

**Comment by Owais24code** [comment]
@Mayuresh-22 
following are list of ideas.

1. fixing the footer 
2. box-like styling for account page searching to more 3D look. 
3. suggestion drawn list when people type in search.

**Comment by Mayuresh-22** [comment]
> @Mayuresh-22 following are list of ideas.
> 
> 1. fixing the footer
> 2. box-like styling for account page searching to more 3D look.
> 3. suggestion drawn list when people type in search.

Okay @Owais24code, I am assigning this issue to you.

Note:
If you want to change the footer style, you need to apply the changes across all pages of the site to maintain consistency.

**Comment by Owais24code** [comment]
@Mayuresh-22 I will do my best to give this the best look.
keeping your suggestion on footer will do it.
