### ISSUE TITLE
the Recommneded password Pattern is not showen 

### ISSUE THREAD

**Issue by Amine2000s** [Mayuresh-22/Minglr#77]
whenever i try to register the first time ,it always pop up to me  that your password is invalid without giving me any guidelines how the password should be 

![Capture d'écran 2024-01-06 003613](https://github.com/Mayuresh-22/Minglr/assets/92222814/eba9c72b-ee1a-4a4b-95ca-678b6bf4f952)

**Comment by 1-ankush-1** [comment]
## Approches to solve this bug.
 - Add a placeholder of required pattern in password input.
 - After submitting the password .
   - if password pattern is wrong add a warning message with the respective password pattern that will be shown below password input tag.
 
- [ ] assign this to me as SWOC S4

**Comment by Mayuresh-22** [comment]
Regex for password was added by @GauriGA.

You can check the reply https://github.com/Mayuresh-22/Minglr/pull/64#issuecomment-1875708508 to know the valid password.

**Comment by Mayuresh-22** [comment]
@1-ankush-1 do you want to work on this issue? 
Your approach is quite correct you'll need to add few checks bellow the password field in the registration form so that user can understand.

For example:
1. Your password must be 8 characters long.
2. At least one uppercase letter.
3. ...
4. ...

Refer: https://github.com/Mayuresh-22/Minglr/pull/64#issuecomment-1875708508

**Comment by 1-ankush-1** [comment]
> @1-ankush-1 do you want to work on this issue? Your approach is quite correct you'll need to add few checks bellow the password field in the registration form so that user can understand.
> 
> For example:
> 
> 1. Your password must be 8 characters long.
> 2. At least one uppercase letter.
> 3. a wild card character
> 4. a number should be there too
> 
> Refer: [#64 (comment)](https://github.com/Mayuresh-22/Minglr/pull/64#issuecomment-1875708508)

i get your requirements . you can assign this issue to me.

**Comment by Mayuresh-22** [comment]
Okay then @1-ankush-1, you can start working on it. I'll assign this issue to you. Also, try to add a custom JavaScript which will help in checking the password requirements if the password entered by the user satisfies it.
Example:
**1. Your password must be 8 characters long.** (Text colour turns green if password length is 8 characters, this happens as the user enters the password)
And so on for other checks.
Once all the required checks have been completed successfully, the user can proceed by clicking on the register button (Till then it will be disabled).

If you have any doubt's feel free to contact.

**Comment by 1-ankush-1** [comment]
> Okay then @1-ankush-1, you can start working on it. I'll assign this issue to you. Also, try to add a custom JavaScript which will help in checking the password requirements if the password entered by the user satisfies it. Example: **1. Your password must be 8 characters long.** (Text colour turns green if password length is 8 characters, this happens as the user enters the password) And so on for other checks. Once all the required checks have been completed successfully, the user can proceed by clicking on the register button (Till then it will be disabled).
> 
> If you have any doubt feel free to contact me.

thanks i will fix this issue.
