### ISSUE TITLE
I would like to add a dark mode into the minglr.

### ISSUE THREAD

**Issue by bhatiaarpit** [Mayuresh-22/Minglr#84]
I would like to add a dark mode into the UI of the Minglr and make changes into the UI which will enhance the look of minglr.
Before
![Screenshot 2024-01-12 234133](https://github.com/Mayuresh-22/Minglr/assets/118626392/cfa87adf-68e6-4918-9efd-2789bf0185fd)
After (its just a preview )

https://github.com/Mayuresh-22/Minglr/assets/118626392/57b3df49-f1b0-4243-8524-9d23b2d12439

Kindly assign this task to me under SWOC.

**Comment by Mayuresh-22** [comment]
Hey buddy @bhatiaarpit, great job! I loved it. I suggest you experiment with different colour combinations and create a PR. I'll assign this issue to you ASAP.

**Comment by bhatiaarpit** [comment]
Thanks brother, on it!

**Comment by Mayuresh-22** [comment]
Are you still working on it?

**Comment by bhatiaarpit** [comment]
Will complete in some days.. actually I got busy in my end sem exams.

**Comment by Mayuresh-22** [comment]
@bhatiaarpit any updates?

**Comment by bhatiaarpit** [comment]
I have added the dark mode in every page but I need to do more 
![Uploading Screenshot 2024-02-10 004705.png…]()
work on design of minglr... can I design a new logo for minglr?

**Comment by bhatiaarpit** [comment]
![Screenshot 2024-02-10 004705](https://github.com/Mayuresh-22/Minglr/assets/118626392/046d6cc2-0b44-4e51-af55-cf4d56300d24)
@Mayuresh-22  I added the dark mode on every page, but I still need to work on the design of minglr. Can I design a new logo for minglr?

**Comment by Mayuresh-22** [comment]
It looks great and I appreciate your work, but can we do something with the navbar? As it should also be a part of the Night mode feature.
Making a new logo for Minglr? Great idea I'll create a new issue for it then...

**Comment by bhatiaarpit** [comment]
Yes, definitely working on the other parts of minglr.

**Comment by bhatiaarpit** [comment]
@Mayuresh-22  Please checkout the changes in minglr, I designed a logo too for minglr. 

https://drive.google.com/file/d/1GLwjy9yMKNrmQc4cjvf4DsdqYDECGajW/view?usp=sharing

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 Please Checkout the changes in minglr, In some there are some issues like CSS isn't loading on account page and on login page, 
And others things are working fine.

https://drive.google.com/file/d/127DdWZkce8N-GLdCcKARiZX1vW0TDSYi/view?usp=drivesdk

**Comment by Mayuresh-22** [comment]
You have done a fabulous work. Even the "Minglr" logo is great; those extra additions make it more attractive. I watched the demo video and almost everything looks perfect, but the CSS not loading especially on `/account.php` will be the result of some file issues (We will look into it).
Make sure the changes are responsive and work on the mobile devices as well.
Else, everything seems good.

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 There's an issue with CSS not loading on the account.php page, while other functionalities are working fine. Minglr is fully responsive on mobile devices.
Checkout the other changes...
https://drive.google.com/file/d/1j9nOfATKwpZdemwNvKS4qwrYMEfjvb5X/view?usp=sharing

**Comment by Mayuresh-22** [comment]
Hey, good work,
I watched the new video (showing mobile devices) and there I saw that the
page layout (primarily of the account page) changes once we change the mode
from light to dark.
Please have a look into it.

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 There is an issue because the CSS for account.php isn't loading correctly.

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 I've addressed all the issues. Take a look at Minglr now.

https://drive.google.com/file/d/1pXc4m5QQ8gp1MM3aW1hdq2Xz_uxG7-EG/view?usp=sharing

**Comment by Mayuresh-22** [comment]
Hey buddy, I watched the demo video and I must say everything looks perfect that's great you've made such a great contribution.
I think you can raise a PR under SWOC24

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 I've initiated a pull request for your review. Kindly check it.

**Comment by Mayuresh-22** [comment]
Successfully solved by #119

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 Thankyou❤️
