### ISSUE TITLE
Footer size and style modification

### ISSUE THREAD

**Issue by Nandini80** [Mayuresh-22/Minglr#85]
I'll make necessary improvements to enhance its appearance.
<img width="947" alt="image" src="https://github.com/Mayuresh-22/Minglr/assets/121488571/66a14b30-9641-42d4-9859-27f85862c96a">

**Comment by Mayuresh-22** [comment]
okay, @Nandini80 nice idea you can go with it. I will assign it to you. Make sure your changes are responsive throughout the devices.

**Comment by Nandini80** [comment]
@Mayuresh-22, I'm having trouble in making changes in style.css file or any other CSS file. No matter how many times I try, only updates to PHP files are showing, not the CSS ones. Any idea why this might be happening?

**Comment by Nandini80** [comment]
@Mayuresh-22  Please reply

**Comment by Nandini80** [comment]
I have updated the styling of the footer. Please check.

<img width="928" alt="image" src="https://github.com/Mayuresh-22/Minglr/assets/121488571/f5200801-dcd6-443b-83ce-a2b71b688e6d">

**Comment by Mayuresh-22** [comment]
Solved by #95 congratulations @Nandini80
