### ISSUE TITLE
Adding LOGO in website

### ISSUE THREAD

**Issue by mansi1309** [Mayuresh-22/Minglr#93]
please assign this issue to me .I would like to add a logo in website.
![image](https://github.com/Mayuresh-22/Minglr/assets/133951716/16d6c943-e0f6-48c6-a8f9-7fd9325afa34)

**Comment by aryasingh258** [comment]
plz assign this issue to me

**Comment by Mayuresh-22** [comment]
hey @mansi1309, what type of logo would you like to add can you explain more about it?

**Comment by Mayuresh-22** [comment]
@mansi1309 any updates?

**Comment by Ashwin145** [comment]
Hey @Mayuresh-22  Please assign this issue to me

**Comment by Mayuresh-22** [comment]
This is already solved, so I am closing this issue.
