### ISSUE TITLE
Registration Form Validation

### ISSUE THREAD

**Issue by Sanjana787** [Mayuresh-22/Minglr#94]
the registration form accepts the user's first name and last name as numeric values whereas it should accept only character values.
![11](https://github.com/Mayuresh-22/Minglr/assets/141259407/7f435dcd-fb6f-42e8-8215-dda5f5ca68d4)
![10](https://github.com/Mayuresh-22/Minglr/assets/141259407/38ea60f3-870e-4108-a92f-6f8a9c32d811)

**Comment by Mayuresh-22** [comment]
Great observation @Sanjana787, you can start working on this issue. I'll assign it to you under SWOC 24

**Comment by Mayuresh-22** [comment]
@Sanjana787 are you still working on the issue?

**Comment by Sanjana787** [comment]
yes I am @Mayuresh-22

**Comment by Mayuresh-22** [comment]
okay make sure you create PR as soon as you are done with it

**Comment by Mayuresh-22** [comment]
This issue is solved by the PR #108
